openapi: 3.0.1
info:
  title: monster-iron-golem
  x-cortex-tag: monster-iron-golem
  x-cortex-custom-metadata:
    alignment: neutral-evil
    type: plant
    challenge_rating: 18
    legendary: true
    armor_class: 18
    hit_points: 269
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-iron-golem
      alias: github-token-test
